### ISSUE TITLE
Prisma engines

### ISSUE THREAD

**Issue by medz** [odroe/prisma-dart#1]
@Ali1Ammar I have done Prisma binary engines download functionality and db push/format. Currently my job is to develop a binary client proxy for query engine, but given that you have already completed https://github.com/Ali1Ammar/prisma-client-dart that is query engine proxy and client generation. I had to reassign work.

Since you've already written the query engine, I think you can just migrate the code over and it will work.

Next, I will use Rust to write Prisma query engine's C APIs dylib to make Prisma for Dart support Flutter.

Regarding the Prisma Data Proxy part, I think we can revisit the distribution of development work after the dylib development is complete.

@medz TODO：

- [ ] A dylib for Prisma query engine written in Rust

@Ali1Ammar TODO:

- [x] Complete the binary part of Prisma query engine.

**Comment by medz** [comment]
@Ali1Ammar I'm in contact with the Prisma ORM official to see if I need to move this repository under the prisma org.

**Comment by medz** [comment]
@Ali1Ammar Can you email me your pub.dev account email address? I will set your permissions in pub.dev on all packages of Prisma ORM.

**Comment by medz** [comment]
@Ali1Ammar Regarding the three engines of Binary, Dynamic Library, and Data Proxy, I have established a good cross-platform interface for them in the `main` branch (to be completed).

The responsibilities of each package are as follows:

1. `orm` is responsible for the runtime, which is the Prisma Client part, the code is platform independent. But bin still needs to proxy `cli` so that developers can type as few command strings as possible.
2. `prisma_cli` is responsible for completing data management and other related command line tools
3. `prisma_query_engine`, for the engine encapsulation of the `orm` package, export and use platform judgment, so that it supports three engines and the flag of the package is all platforms.
4. `prisma_query_engine_dylib` has a built-in toolchain for the C API written by `Prisma Engines`, and `EngineDynamicLibrary` is automatically generated during development.

I think you're working on the `prisma-engine` branch without needing to have the `main` branch and make some changes to the code.

At the same time I forked the `prisma_engine_dylib` branch for the development of Dynamic Engine.

**Comment by medz** [comment]
I think the Engine interface part is what we need to complete together. next, I will focus on development of Dynamic Library Engine and supplement the Engine interface.

**Comment by Ali1Ammar** [comment]
I have a working version of the binary engine inside https://github.com/odroe/prisma/tree/query-engine/orm/lib/src/engine
I will merge this implementation in` prisma_query_engine/lib/src/native/binary `
but I need to access `configure` class from `prisma_cli/lib/src/configure.dart`
so I think we need I new package for the shared code between all

**Comment by medz** [comment]
@Ali1Ammar It is possible to create new packages for code sharing. I've also been wondering how to share the configuration.

Loading the configuration requires IO operations, which may affect the Dart Web and Flutter Web platforms, but I think a shared package with IO operations can be implemented first. We'll discuss how to deal with the web platform when we're done developing Prisma Data Proxy.

**Comment by Ali1Ammar** [comment]
@medz for the web we could generate the config as dart file with the generate command but for now I will just add todo for that

**Comment by medz** [comment]
@Ali1Ammar 👌 The i'm  idea of web platform support is to only allow Prisma Data Proxy engine drivers.

But that's after we've done the Binary and DynamicLibrary drivers.

**Comment by Chris-Sechri** [comment]
Hi guys, i was so excited to use this package until  the following command `dart run orm generate` is not working, so i can't generate the client.
Can you help me to fix that please ?

**Comment by Ali1Ammar** [comment]
hello @Chris-Sechri 
 this package is still under heavy development and we still didn't releases any version for public use

**Comment by Chris-Sechri** [comment]
Hello @Ali1Ammar, okay no problem, we will wait 🙃
