### ISSUE TITLE
About query engine implementation

### ISSUE THREAD

**Issue by medz** [odroe/prisma-dart#106]
We are refactoring the client implementation of the query engine, the current plan is:

Option One:
1. Create `prisma_engine_core` for unified GraphQL query.
2. Create `prisma_engine_binray` to implement the operation of the binary engine, and then call `prisma_engine_core` to implement the query client.
3. Create `prisma_engine_dataproxy` to implement the engine implementation of Prisma Data Proxy. It mainly calls `prisma_engine_core` queries, but it will handle some special errors of data proxy.
4. Create `prisma_engine_library` to implement the dynamic library engine
5. Create `prisma_engine_flutter` to implement Flutter's dynamic library support.

Option II:
1. Create `prisma_engine` to implement 1-4 in Scheme 1
2. Create `prisma_engine_flutter` to realize the binding between the dynamic library and Flutter.

Q: Why create a separate engine package?
A: Developers can choose different package implementations according to their own needs

There are also the following modifications:

1. Change the orm package to dev dependency
2. Create the `prisma_client` package as an official dependency of the runtime.

**Do you have any suggestions?**

**Comment by medz** [comment]
Option 3:

Keep the status quo and use different entry files to distinguish

**Comment by odunboye** [comment]
Option 1
