### ISSUE TITLE
Count seems to be missing

### ISSUE THREAD

**Issue by odunboye** [odroe/prisma-dart#110]
Hi @medz , Thank you for a nice package 
Please is there a way to do count on objects without loading the entire objects into memory?
e.g in Sql one would normally do 
`SELECT COUNT(ProductID) AS NumberOfProducts FROM Products;`
Thanks once again

**Comment by medz** [comment]
Using the `queryRaw` method,  But is this a Prisma problem? Or is it a bug in my implementation? If it's my mistake, I think I'll fix it. If Prisma's own strategy is to load the entire table field, then you can use `queryRaw` to optimize your query.

**Comment by odunboye** [comment]
@medz thanks for your prompt response
the following line for `queryRaw` throws the exception below
code :
`final result = await prisma.$queryRaw('SELECT * FROM payment;');`

exception:
` PrismaClientKnownRequestError(
        message: Error parsing GraphQL query: query parse error: Parse error at 1:72
      Unexpected `:[Punctuator]`
      Expected `Name`, `:` or `)`
      ,
        code: UNKNOWN,
        meta: null,
        clientVersion: 2.6.2,
      )`

Could you help with an example?

**Comment by medz** [comment]
In the beta version of 3.0 (https://pub.dev/packages/orm/versions/3.0.0-beta.1) I solved it, now just need:

```dart
final int count = await prisma.user.aggregate().$count().id();
```

**Comment by medz** [comment]
@odunboye https://prisma.pub/docs/aggregation.html
