### ISSUE TITLE
Exception: Not found model

### ISSUE THREAD

**Issue by jackstefansky** [odroe/prisma-dart#138]
I get following exception trying to create `User` object in sqlite db.

Failing part:

```
_prismaClient.user.create(
      data: UserCreateInput(
        email: email,
        passwordHash: passwordHash,
        firstName: firstName,
        lastName: lastName,
      ),
    );
```

Output:
```
Exception: Not found User
#0      UserModelDelegateExtension.create.<anonymous closure> (package:prisma_client/prisma_client.dart:6979:13)
#1      _rootRunUnary (dart:async/zone.dart:1406:47)
#2      _CustomZone.runUnary (dart:async/zone.dart:1307:19)
<asynchronous suspension>
```

I think the case might be generated code ( json is null )
```
...
final future = query(UserScalarFieldEnum.values.toGraphQLFields()).then(
        (json) => json is Map
            ? User.fromJson(json.cast<String, dynamic>())
            : throw Exception('Not found User'));
...
```

**Comment by nikosportolos** [comment]
I get a similar error.

My table schema as defined in `schema.prisma`:
```
datasource db {
  provider = "sqlserver"
  url      = env("DATABASE_URL")
}
```
```
model User {
  id         String   @id(map: "PK_User") @db.NVarChar(36)
  email      String   @unique @db.NVarChar(100)
  first_name String   @db.NVarChar(100)
  last_name  String   @db.NVarChar(100)
  joined_on  DateTime @default(now())
}
```

The data I'm trying to insert into the database:
```dart
 await prisma.user.create(
      data: UserCreateInput(
        id: '61d4c0a6-a513-4eac-b754-abf4bfe913c7',
        email: 'admin@email.com',
        firstName: 'Nikos',
        lastName: 'Portolos',
        joinedOn: DateTime.now(),
      ),
    );
```

And this is the error I get in [lib/src/client/model_delegate.dart:36](https://github.com/odroe/prisma-dart/blob/88e55b7296614ff63ae321c3d92c8131c93059b0/lib/src/client/model_delegate.dart#L36) :

`"Invalid DateTime: '2023-03-06T23:31:35.908432' (must be ISO 8601 compatible). Underlying error: premature end of input"`
```
Error in query graph construction: QueryParserError(QueryParserError { path: QueryPath { segments: ["Mutation", "createOneUser", "data"] }, error_kind: InputUnionParseError { parsing_errors: [QueryParserError { path: QueryPath { segments: ["Mutation", "createOneUser", "data", "UserCreateInput", "joined_on"] }, error_kind: ValueParseError("Invalid DateTime: '2023-03-06T23:31:35.908432' (must be ISO 8601 compatible). Underlying error: premature end of input") }, QueryParserError { path: QueryPath { segments: ["Mutation", "createOneUser", "data", "UserUncheckedCreateInput", "joined_on"] }, error_kind: ValueParseError("Invalid DateTime: '2023-03-06T23:31:35.908432' (must be ISO 8601 compatible). Underlying error: premature end of input") }] } })
```

**Comment by medz** [comment]
> I get a similar error.
> 
> My table schema as defined in `schema.prisma`:
> 
> ```
> datasource db {
>   provider = "sqlserver"
>   url      = env("DATABASE_URL")
> }
> ```
> 
> ```
> model User {
>   id         String   @id(map: "PK_User") @db.NVarChar(36)
>   email      String   @unique @db.NVarChar(100)
>   first_name String   @db.NVarChar(100)
>   last_name  String   @db.NVarChar(100)
>   joined_on  DateTime @default(now())
> }
> ```
> 
> The data I'm trying to insert into the database:
> 
> ```dart
>  await prisma.user.create(
>       data: UserCreateInput(
>         id: '61d4c0a6-a513-4eac-b754-abf4bfe913c7',
>         email: 'admin@email.com',
>         firstName: 'Nikos',
>         lastName: 'Portolos',
>         joinedOn: DateTime.now(),
>       ),
>     );
> ```
> 
> And this is the error I get in [lib/src/client/model_delegate.dart:36](https://github.com/odroe/prisma-dart/blob/88e55b7296614ff63ae321c3d92c8131c93059b0/lib/src/client/model_delegate.dart#L36) :
> 
> `"Invalid DateTime: '2023-03-06T23:31:35.908432' (must be ISO 8601 compatible). Underlying error: premature end of input"`
> 
> ```
> Error in query graph construction: QueryParserError(QueryParserError { path: QueryPath { segments: ["Mutation", "createOneUser", "data"] }, error_kind: InputUnionParseError { parsing_errors: [QueryParserError { path: QueryPath { segments: ["Mutation", "createOneUser", "data", "UserCreateInput", "joined_on"] }, error_kind: ValueParseError("Invalid DateTime: '2023-03-06T23:31:35.908432' (must be ISO 8601 compatible). Underlying error: premature end of input") }, QueryParserError { path: QueryPath { segments: ["Mutation", "createOneUser", "data", "UserUncheckedCreateInput", "joined_on"] }, error_kind: ValueParseError("Invalid DateTime: '2023-03-06T23:31:35.908432' (must be ISO 8601 compatible). Underlying error: premature end of input") }] } })
> ```

This is a separate error. For the time being, you can use 'DateTime. now(). toUtc()' to make it correct. I think I have thought of ways to fix the problem of short time.

**Comment by nikosportolos** [comment]
@medz Yes, you're right. Thanks!

**Comment by medz** [comment]
> must be ISO 8601 compatible). Underlying error: premature end of input
Can you create an issue for me with this question? I think it needs to be tagged because the Prisma engine always expects time in UTC+0.

Flag it so I can fix it when I'm not busy or wait for another collaborator to fix it.
