### ISSUE TITLE
$queryRaw and $executeRaw seem to always return null

### ISSUE THREAD

**Issue by craiglabenz** [odroe/prisma-dart#177]
Both `$queryRaw` and `$executeRaw` seem to always return `null`. For `$executeRaw`, that leads to a fatal exception, as `null` is not a subtype of `FutureOr<int>`.

**`$queryRaw`** example:

```dart
final result = await db.$queryRaw('SELECT NOW()');
print(result); // null
```

**`$executeRaw`** example:

```dart
final result = await db.$queryRaw(r'UPDATE table WHERE id=1 SET column=$1', parameters: ['value']);
// exception: type 'Null' is not a subtype of type 'FutureOr<int>'
```

Perhaps I'm holding it wrong?

Thanks for working on this library, by the way! 💙

**Comment by medz** [comment]
I'm investigating related issues~Thank you for your attention.
