### ISSUE TITLE
Automatically downloading Node

### ISSUE THREAD

**Issue by medz** [odroe/prisma-dart#18]
RobertCraigie/prisma-client-py#454 

There is a good proposal in Prisma for python. At the same time, it can reduce unnecessary repetitive development work and let us focus more on generator and runtime development.

**Comment by jacobaraujo7** [comment]
Can't we download the node to solve the problem of downloading the binary and then delete it?

**Comment by medz** [comment]
> Can't we download the node to solve the problem of downloading the binary and then delete it?

The idea in `prisma-cli-py` is that the Prisma command part uses Prisma official Prisma CLI (developed with Node.js), while we focus on Prisma runtime and client development.

This question is just for discussion, because Prisma for Dart CLI works well (although there are several commands that are not developed).

If we introduce Prisma CLI (Node.js), this will definitely ease our maintenance efforts.

**Comment by utamori** [comment]
First of all, thanks for this great project

Implementing all of Prisma's commands seems like a daunting task
It is also hard to adapt to new commands.

It just doesn't seem sustainable.

> The idea in prisma-cli-py is that the Prisma command part uses Prisma official Prisma CLI (developed with Node.js), while we focus on Prisma runtime and client development.

I completely agree with that idea.

**Comment by medz** [comment]
Maybe we can create a draft to experiment with it, I believe it's far better to keep the toolchain intact than maintaining the CLI ourselves.

But from another point of view, as a Dart or Flutter developer, many people may not want to silently install a Node in his/her computer (that is, it is not a global one, but a real project path to Prisma for Dart).
