### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by vfiruz97** [odroe/prisma-dart#208]
# Cannot generate .g.dart
Error: Null check operator used on a null value
Dart SDK version: 2.19.6 (stable) (Tue Mar 28 13:41:04 2023 +0000) on "macos_x64"

<img width="483" alt="image" src="https://user-images.githubusercontent.com/43540889/235161793-55e63bfb-ce7e-40ad-bdd3-39d65e306bd0.png">

<img width="279" alt="image" src="https://user-images.githubusercontent.com/43540889/235162090-8050f968-4037-4610-89fa-6ba1db04cb69.png">

<img width="447" alt="image" src="https://user-images.githubusercontent.com/43540889/235162162-6bfabb24-bf06-45e5-ba1e-79e762fd6054.png">

**Comment by vfiruz97** [comment]
<img width="377" alt="image" src="https://user-images.githubusercontent.com/43540889/235162856-88871b04-f740-4e61-b52f-0670c76de94c.png">

**Comment by vfiruz97** [comment]
@medz Please look at this Issue [#208](https://github.com/odroe/prisma-dart/issues/208)
I cannot generate .g.dart for dart prisma
what could be going wrong?

**Comment by medz** [comment]
@vfiruz97 I will investigate this issue as soon as possible

**Comment by medz** [comment]
@vfiruz97 I investigated the word issue exactly as you screenshot, and it always works fine. I will submit a branch dedicated to this issue later.

**Comment by medz** [comment]
github: https://github.com/odroe/prisma-dart/tree/208-null-check-operator-used-on-a-null-value

#### General info

- Dart 2.19.4 (stable) (Tue Mar 7 09:58:46 2023 +0000) on "macos_x64"
- on macos / Version 13.3.1 (a) (Build 22E772610a)
- locale is zh-Hans-CN

#### Project info

- sdk constraint: '>=2.19.4 <3.0.0'
- dependencies: json_annotation, orm
- dev_dependencies: build_runner, json_serializable, lints, test

**Comment by medz** [comment]
<img width="570" alt="image" src="https://user-images.githubusercontent.com/5564821/235833309-87fe5ba9-b7b4-4b70-8a72-ee042c0c6d7b.png">
<img width="947" alt="image" src="https://user-images.githubusercontent.com/5564821/235833419-c9489b05-5f49-4a96-b559-86dd2ab7cae4.png">

**Comment by vfiruz97** [comment]
@medz What version of NodeJ installed matters?
In my case 
node v14.19.1
npm 6.14.16
npx 6.14.16

**Comment by medz** [comment]
@vfiruz97 The NodeJS version doesn't matter, the normal LTS version will do.

I can't seem to reproduce it, can you create a repo that minimally exhibits this problem? Then I come to test and find out the problem.

**Comment by vfiruz97** [comment]
@medz thank you for supporting my issue. I fixed this. The core problem is unknown because I solved it by running command in terminal out of VSCode. I think it was related to VSCode terminal. I think it blocks downloading engine from CDN. After solving outside VSCode now it start generating even inside VSCode terminal. 
I will close this issue. I hope this will be the most used ORM package for Dart and the fluent queries makes me to try it. I will be try this soon ))

**Comment by medz** [comment]
I'm glad you found the problem. Perhaps the s3 CDN of the Prisma engine does not cover the network problems caused by some regions. Anyway, I'm glad that you solved this problem. The real Prisma ORM can only be obtained by the union-types support of Dart 3. Now it is a helpless compromise version.

**Comment by kyugao** [comment]
> @medz thank you for supporting my issue. I fixed this. The core problem is unknown because I solved it by running command in terminal out of VSCode. I think it was related to VSCode terminal. I think it blocks downloading engine from CDN. After solving outside VSCode now it start generating even inside VSCode terminal. I will close this issue. I hope this will be the most used ORM package for Dart and the fluent queries makes me to try it. I will be try this soon ))

I meet this issue. I try to generate client inside and outside vscode, both failed. 
![image](https://github.com/medz/prisma-dart/assets/1071977/a2d4706e-1e82-4bd9-9bb6-92c2dda43e2c)

**Comment by medz** [comment]
@kyugao v3.4.5 version puhlished, fixed the bug.
