### ISSUE TITLE
I can't run a query

### ISSUE THREAD

**Issue by anisioisidoro** [odroe/prisma-dart#214]
I added prism in my flutter project and I am getting this error

Can you tell me what am I doing wrong?
![erro](https://user-images.githubusercontent.com/38157703/236759971-23954757-e2dd-4432-947f-2636c2d81bbf.png)

try {
     final user = await prisma.user.create(
       data: UserCreateInput(
         name: 'Alice',
         email: 'alice@prisma.pub',
       ),
     );

     print(user);
   } finally {
     await prisma. $disconnect();
   }

**Comment by medz** [comment]
@anisioisidoro Currently, Flutter only supports the Data Proxy engine. Library engine is still under development (I'm new to rust and progress is slow)

**Comment by pedromassango** [comment]
Hello @medz do you have any working Flutter example/resources in how to use Data proxy with Flutter?

**Comment by ken47** [comment]
The README indicates that the Library Engine is supported on Flutter Native only. Are you using Flutter Web?

**Comment by medz** [comment]
> The README indicates that the Library Engine is supported on Flutter Native only. Are you using Flutter Web?

Data proxy service does not support spanning requests, exposing your database to the public network is a very dangerous thing.
