### ISSUE TITLE
Using lowercase keywords in `schema.prisma` cannot generate clients correctly

### ISSUE THREAD

**Issue by moepoi** [odroe/prisma-dart#26]
Hello, I just tried this package and followed the README but I get this error when I run the command `dart run orm generate`

![image](https://user-images.githubusercontent.com/29736957/191211590-4a412f10-7b6b-4525-8cb3-06fca62f7806.png)

**Comment by medz** [comment]
@moepoi See https://github.com/odroe/prisma-dart#model-deserialize-why-run-build_runner-build

Steps:
1. Add `json_serializable` package - `dart pub add json_serializable -d`
2. Add `build_runner` package - `dart pub add build_runner -d`
3. Run `build_runner build` command - `dart run build_runner build`

reason:
Type-safe input and output need to be done using `json_annotation`.
> There are currently no plans to remove it, because `json_annotation` works well, although it can't be used after running `dart run orm generate`. But at the moment we don't have the manpower to develop a JSON serializer on its own and can only rely on `json_annotation` to run.

**Comment by medz** [comment]
@moepoi 😫, it's a bug

Reason, use lowercase keywords in `schema.prisma`

**Comment by medz** [comment]
I checkout a new branch to fix it

**Comment by medz** [comment]
@moepoi Fixed in `2.2.1` version
