### ISSUE TITLE
How to use this package

### ISSUE THREAD

**Issue by Golabe** [odroe/prisma-dart#3]
How to use this package

**Comment by Ali1Ammar** [comment]
we will release a working version in the following days

**Comment by medz** [comment]
Available version releases also require:
1. [ ] `db pull` command
2. [ ] generate command
3. [ ] GraphQL SDL builder
4. [ ] GraphQL responses are converted to models

Hi @Golabe:

 I and @Ali1Ammar  couldn't use our full working time to develop. But I believe the first available version will be released soon.

Currently, I'm developing with the vast majority of my work.

**Comment by medz** [comment]
Probably my problem, been dissatisfied with the previous package organization. The 2.0 refactoring has been started recently. @Ali1Ammar  Sorry, I removed most of your previous work in this refactoring. But I am quite satisfied with the current code structure, forgive my code cleanliness and obsessive-compulsive disorder (just kidding 😊)

**Comment by medz** [comment]
@Ali1Ammar @Golabe 

Already available in version 2.0.0-dev.4. But still the following problems:

1. `db pull` has not been completed
2. Model deserialization has not been completed yet, the current model code returns `dynamic` type

**Comment by medz** [comment]
See https://github.com/odroe/prisma-dart/releases/tag/2.0.0
