### ISSUE TITLE
feat: automatic disconnect

### ISSUE THREAD

**Issue by tomassasovsky** [odroe/prisma-dart#33]
Since Dart 2.17, `Finalizer` is available. This should be added to the generated `PrismaClient` class. Here's the reference to the Finalizer:
https://api.flutter.dev/flutter/dart-core/Finalizer-class.html

**Comment by medz** [comment]
Prisma Client just proxy Query Engine, we should add it to the engine `start` function.

**Comment by medz** [comment]
@tomassasovsky I implemented it in #35, but it's currently in the `preview-features` stage. If it evolves over a month, users are not causing serious problems with this feature. This feature will land in the official version.

**Comment by medz** [comment]
A version containing it in preview will be released in the next few days.
