### ISSUE TITLE
feat(ci): workflow for dart packages that include `prisma-dart`

### ISSUE THREAD

**Issue by tomassasovsky** [odroe/prisma-dart#38]
Since `generated/` is excluded from Git, GitHub Actions fails due to the unavailability of the `prisma_client.dart` file.
There should be a workflow we can use to generate this from within GitHub Actions.

**Comment by medz** [comment]
https://github.com/odroe/prisma-dart/blob/main/.github/workflows/test.yaml#L17 

This should be up to the user, such as the cache engine and cache in GitHub Actions. Download the engine and generate prisma client files via setps.run when there is no cache.
