### ISSUE TITLE
Error: Required named parameter 'logEmitter' must be provided.

### ISSUE THREAD

**Issue by Rodsevich** [odroe/prisma-dart#45]
Error: Required named parameter 'logEmitter' must be provided.
        final _i2.Engine engine = _i2.BinaryEngine(
                                                  ^

This happens on the lastest version (2.3.1) on generated prisma_client.dart

**Comment by medz** [comment]
@Rodsevich You try to rerun the `dart run orm generate` command to fix the problem.

**Comment by Rodsevich** [comment]
yeah, I ran:
```
dart pub get
dart run orm generate
dart run build_runner build --delete-conflicting-outputs
```

**Comment by medz** [comment]
@Rodsevich 
<img width="609" alt="image" src="https://user-images.githubusercontent.com/5564821/194813403-a816644e-74c7-49c5-ae8e-d1c1220b1717.png">
Can you provide a minimal reproduction example? I created a new Dart project and then used your command steps and still haven't found the problem.

**Comment by Rodsevich** [comment]
Our schema.prisma begins with:
```
generator client {
  provider        = "prisma-client-dart"
  previewFeatures = ["interactiveTransactions"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL_WITH_SCHEMA")
}

model Entity {

```

**Comment by medz** [comment]
https://user-images.githubusercontent.com/5564821/194820953-5ec261a4-e936-49e9-8387-8f70922e5a78.mov

**Comment by Rodsevich** [comment]
https://pastebin.com/73SS2sJB
This is schema.prisma we have. If the bug doesn't replicate with that, do you know a way I can get rid of it on the project?

**Comment by medz** [comment]
This problem doesn't seem to be related to the schema, you try to regenerate the client after changing the orm version to 2.3.1 in `pubspec.yaml`. I'll copy your schema and keep trying.

**Comment by medz** [comment]
I copied your schema to try. There were no problems either. Can I see the contents of your pubspec.yaml?
