### ISSUE TITLE
Unhandled exception: type 'Null' is not a subtype of type 'String' in type cast

### ISSUE THREAD

**Issue by LucaBarden** [odroe/prisma-dart#52]
I've been trying to get the orm to work. I am able to create the initial config files via "flutter pub run orm init" but when I try to use db push with the example models from the Website I get the following Errors.

<img width="1418" alt="image" src="https://user-images.githubusercontent.com/57015324/197545151-28a5d1d9-0e72-4f98-b6b2-f336e3e72108.png">

Is this a common Issue or does it have to do with my System?

Im working on an M1 Mac. Just if that's a necessary info.

**Comment by medz** [comment]
I'll fork your schema and create a project that uses sqlite for validation. Please wait.

**Comment by medz** [comment]
@LucaBarden Fixed in [2.4.1](https://pub.dev/packages/orm/changelog#241) version
