### ISSUE TITLE
When there is an error in the generate command. Print the prisma error message to the console.

### ISSUE THREAD

**Issue by fatalaa** [odroe/prisma-dart#58]
At the moment, if the schema triggers an error from Prisma. The error will be something like this:
```
FormatException: Unexpected end of input (at character 1)
```

This happens because the generate command doesn't consider the `stderr`'s value before trying to parse the document from the JSON response.

The solution could be that before the generator command tries to parse the JSON response, it could check the stderr's value and in case it's not empty. It could print the actual error message from Prisma.

**Comment by medz** [comment]
@fatalaa Is there an error output log?

**Comment by medz** [comment]
@fatalaa or the most simplified example

**Comment by fatalaa** [comment]
```
generator client {
  provider        = "prisma-client-dart"
  previewFeatures = ["interactiveTransactions"]
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

model Participant {
  id        Int       @id @default(autoincrement())
  email     String    @unique
  avatar    String?
  name      String
  createdAt DateTime  @default(now())
  updatedAt DateTime  @updatedAt
  Project   Project[]
}

model Project {
  id              Int         @id @default(autoincrement())
  title           String
  description     String
  maxParticipants Int
  owner           Participant @relation(fields: [ownerId], references: [id])
  ownerId         Int
  createdAt       DateTime    @default(now())
  updatedAt       DateTime    @updatedAt
}
```

**Comment by fatalaa** [comment]
I actually had a patch for this. Didn't expect you to fix this so soon.

Thank you anyway.

**Comment by medz** [comment]
> I actually had a patch for this. Didn't expect you to fix this so soon.
> 
> Thank you anyway.

@fatalaa I'm just showing the error message in plain sight, if your patch handles the error better you can create a PR to request a merge.

**Comment by fatalaa** [comment]
I implemented it almost the same way as you did 🙂
