### ISSUE TITLE
Connecting to Atlas MongoDB

### ISSUE THREAD

**Issue by boosey** [odroe/prisma-dart#62]
I have been struggling for 3 days to connect to either local or Atlas Mongo. I continue to receive a Connection Refused with no error code. I have tried every variation of the connection string including adding authSource=admin. The connection string works fine in mongosh and Compass.

Here is my current connection string: 
mongodb+srv://xxxxxx:yyyyyy@xxxcluster.ki1jpzv.mongodb.net/cbm?retryWrites=true&w=majority&ssl=true&authSource=admin

This is the error I get back:
PrismaClientInitializationError:
  message: Failed to start the query engine: Connection refused
  errorCode: null
  clientVersion: 2.4.3

**Comment by medz** [comment]
@boosey https://www.prisma.io/docs/concepts/database-connectors/mongodb#connection-details

**Comment by medz** [comment]
@boosey Maybe related to OpenSSL, I will create a similar scenario to test the MongoDB connection for further testing.

**Comment by sunlimiter** [comment]
@medz  I have a similar problem
mongodb
```
mongodb://xxxx:xxxx@localhost:27017/?authSource=xxxxx&ssl=false
```
```
PrismaClientKnownRequestError(
  message: Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: RawDatabaseError { code: "unknown", message: "Command failed (Unauthorized): command find requires authentication)" } }),
  code: UNKNOWN,
  meta: null,
  clientVersion: 2.4.3,
)
```

**Comment by medz** [comment]
@sunlimiter 我没使用 mongdb，我感觉得等到我周末空了才能测试 mongdb😂，要修复这个问题得与 Prisma JS/TS 客户端进行连接数据的对比才能修复。这几天公司加班严重，工作日没啥时间处理这个问题。

**Comment by extrordinaire** [comment]
I'll take a look! WML 😁

**Comment by sunlimiter** [comment]
:open_mouth:
@medz 我把文档看了几遍，发现是调用了生产环境的配置文件，我只改了prisma/development.dart下面的配置，lib/prisma_configurator.dart里面默认生成的，导致运行的时候连接失败
没发现哪里设置开发模式，生产模式，如果可以的话，建一个mongo的demo最好啦

**Comment by medz** [comment]
> 😮 @medz 我把文档看了几遍，发现是调用了生产环境的配置文件，我只改了prisma/development.dart下面的配置，lib/prisma_configurator.dart里面默认生成的，导致运行的时候连接失败 没发现哪里设置开发模式，生产模式，如果可以的话，建一个mongo的demo最好啦

我没找到 Dart 项目比较好的配置方式，dotenv 问题也很大。我常用方法是删除 prisma_configurator.dart
