### ISSUE TITLE
Error: The method 'fromJson' isn't defined for the class 'Type'

### ISSUE THREAD

**Issue by sunlimiter** [odroe/prisma-dart#63]
* prisma_client.dart

![image](https://user-images.githubusercontent.com/4102545/200025830-692be269-3fd5-4899-b313-e3a03a0aa682.png)
![image](https://user-images.githubusercontent.com/4102545/200025915-a6ccf40b-6fa3-4e68-9ab9-b948d8e0fec8.png)
```
Flutter 3.3.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ffccd96b62 (10 weeks ago) • 2022-08-29 17:28:57 -0700
Engine • revision 5e9e0e0aa8
Tools • Dart 2.18.0 • DevTools 2.15.0
```
mongodb

orm: ^2.4.3

**Comment by medz** [comment]
@sunlimiter Can you provide a reproducible `schema.prisma` content?

**Comment by sunlimiter** [comment]
```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider        = "prisma-client-dart"
  previewFeatures = ["interactiveTransactions"]
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}


model VideoLog {
  id    String @id @default(auto()) @map("_id") @db.ObjectId
  extendData String
}
```

> @sunlimiter你能提供一个可重现的`schema.prisma`内容吗？

**Comment by lucascardo12** [comment]
Hi, I'm also having the same problem as described.

**Comment by medz** [comment]
@sunlimiter @lucascardo12 Please try the `2.4.4-dev.0` version to verify whether it is fixed, I have fixed it by myself. Waiting for feedback on this issue, if it has been fixed, a new fixed version will be released. https://pub.dev/packages/orm/versions/2.4.4-dev.0

**Comment by sunlimiter** [comment]
> @sunlimiter @lucascardo12 Please try the `2.4.4-dev.0` version to verify whether it is fixed, I have fixed it by myself. Waiting for feedback on this issue, if it has been fixed, a new fixed version will be released. https://pub.dev/packages/orm/versions/2.4.4-dev.0

Okay, problem solved

**Comment by medz** [comment]
这个问题似乎并没有完全修复，字段是有问题的，周末统一处理，Raw 查询得单独写codegen

**Comment by sunlimiter** [comment]
没注意到其他问题，被连接鉴权那里卡住了，坐等修复

**Comment by medz** [comment]
@skillLan @Ali1Ammar @extrordinaire Hi guys, do you have time to deal with this? Including #62 I've been so busy lately that I probably won't have time until this weekend.

**Comment by zeucxb** [comment]
@medz Problem solved here! tks.
