### ISSUE TITLE
QueryRaw unavailable

### ISSUE THREAD

**Issue by jrbytes** [odroe/prisma-dart#66]
Hello, I need to use queryRaw, but it not see in options available in instance prisma.
I think it's essential if some of the orm's features for handling data aren't working properly at this stage of the library.
<img width="720" alt="Screenshot 2022-11-19 at 16 04 15" src="https://user-images.githubusercontent.com/26124887/202867313-5951fa7c-6843-418e-be68-f29520e4d233.png">

**Comment by Rekshot21** [comment]
I have the same problem

**Comment by medz** [comment]
@jrbytes @Rekshot21 The feat released in `2.5.0` version
