### ISSUE TITLE
BUG - Model relation deserialization is a must

### ISSUE THREAD

**Issue by medz** [odroe/prisma-dart#7]
The relationship of the model should not be required, but optional.

**Comment by medz** [comment]
@Ali1Ammar Can you solve this problem? I can't continue to maintain this project for the next time because the company has a more important project that needs me. This is a small problem, making the fields of the model relationship optional. A new version can be released after the fix. 🙏

**Comment by Ali1Ammar** [comment]
fixed

**Comment by medz** [comment]
Fixed in `2.0.1` version: https://github.com/odroe/prisma-dart/releases/tag/2.0.1
