### ISSUE TITLE
Feature: add support for migration?

### ISSUE THREAD

**Issue by clovett** [odroe/prisma-dart#73]
How does this library help me with migration of databases that are already deployed on customer's machines, I need to rev the schema, let's say for example, change a column name, or add a new column, or change the column type.  Does this library help create the "migration" code needed to apply changes on the deployed on customer's machine's at runtime once customer has upgrated the version of the app?

**Comment by medz** [comment]
There is such a plan, but because there are too many remaining problems. Including language restrictions, perhaps in the planned 3.0 release.

**Comment by medz** [comment]
@clovett The new 3.0 version will be a pure Prisma client, using the official Prisma CLI, so, you just follow https://www.prisma.io/docs/concepts/components/prisma-migrate 🎉
