### ISSUE TITLE
Wrong text "Download binray query engine"

### ISSUE THREAD

**Issue by AndryHTC** [odroe/prisma-dart#78]
The console should print `Download binary query engine` instead of `Download binray query engine`

:)

**Comment by medz** [comment]
@AndryHTC `Download binary query engine` and `Download binray query engine` difference？

**Comment by AndryHTC** [comment]
The difference is **Binray**... Or maybe it's bin in a form of a ray... I don't know 😛

**Comment by medz** [comment]
@AndryHTC 😂Got it, it will be fixed in the next version. The word is misspelled.

**Comment by AndryHTC** [comment]
> @AndryHTC 😂Got it, it will be fixed in the next version. The word is misspelled.

Great! Also **configuration** is misspelled **configuretion** in the docs!
