### ISSUE TITLE
Development environment not working

### ISSUE THREAD

**Issue by AmoonPod** [odroe/prisma-dart#80]
I'm trying to use the development DATABASE_URL that I put into the `prisma/development.dart` file, but when I run everything in debug mode, Prisma still uses the production DATABASE_URL in `lib/src/prisma_configurator.dart`.

What am I missing here?

**Comment by medz** [comment]
@AmoonPod There are many disadvantages for environment configuration now, and I am looking for a painless and universal configuration method in Dart & Flutter.

**Comment by medz** [comment]
@AmoonPod If in a docker container, I recommend removing `prisma_configurator.dart` and `development.dart`

**Comment by medz** [comment]
https://prisma.pub/docs/configuration.html
