### ISSUE TITLE
Assert error in GraphQLArg class.

### ISSUE THREAD

**Issue by jacobaraujo7** [odroe/prisma-dart#9]
This assertion make no sense to me.
<img width="641" alt="image" src="https://user-images.githubusercontent.com/4047813/188334148-f812f5fd-814f-4287-a028-d8b34981c685.png">

If not required, the assert will raise an error.

SUGGESTION: `isRequired ? value != null : true`

**Comment by Ali1Ammar** [comment]
thank you for informing us, I fix it
