### ISSUE TITLE
the generated file is broken . Error  Duplicated parameter name

### ISSUE THREAD

**Issue by hassandaru** [odroe/prisma-dart#97]
`model User {
  id    Int   @id @default(autoincrement())
  email String @db.VarChar(200) @unique
  password  String? @db.VarChar(200)
  access  String? @db.VarChar(100)
  createdAt  DateTime?
  updatedAt  DateTime?
  modules Module[]
  questionResponses QuestionResponse[]
}

model Module {
  id    Int  @id @default(autoincrement())
  name  String @db.VarChar(200) @unique
  createdBy User    @relation(fields: [created_by], references: [id])
  created_by Int
  createdAt  DateTime?
  updatedAt  DateTime?
  questions Question[]
}

model Question {
  id    Int         @id @default(autoincrement())
  module Module     @relation(fields: [module_id], references: [id])
  module_id Int @unique
  question_text  String? @db.VarChar(2000)
  answer_options  String? @db.VarChar(2000)
  correct_answer  String? @db.VarChar(2000)
  createdAt  DateTime?
  updatedAt  DateTime?
  questionResponses QuestionResponse[]
}

model QuestionResponse {
  id    Int     @default(autoincrement())
  question Question    @relation(fields: [question_id], references: [id])
  question_id Int @unique
  participant User    @relation(fields: [participant_id], references: [id])
  participant_id Int
  question_text  String? @db.VarChar(2000)
  answer_options  String? @db.VarChar(2000)
  correct_answer  String? @db.VarChar(2000)
  grade  String?
  feedback  String? @db.VarChar(3000)
  createdAt  DateTime?
  updatedAt  DateTime?
  @@unique([question_id, participant_id])
  @@id([id, question_id, participant_id])

}`

theis creates the required files, however the code does not run. Unsure why as its fairly simple 
`lib/prisma_client.dart:1579:13: Error: Duplicated parameter name 'id_question_id_participant_id'.
            id_question_id_participant_id,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/prisma_client.dart:1575:13: Context: Other parameter named 'id_question_id_participant_id'.
            id_question_id_participant_id,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/utils.dart:6:8: Error: Error when reading 'lib/model/user.dart': The system cannot find the path specified.

import 'package:skill_up_backend/model/user.dart';
       ^
lib/prisma_client.freezed.dart:45659:11: Error: 'id_question_id_participant_id' is already declared in this scope.
      get id_question_id_participant_id => throw _privateConstructorUsedError;
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/prisma_client.freezed.dart:45656:11: Context: Previous declaration of 'id_question_id_participant_id'.
      get id_question_id_participant_id => throw _privateConstructorUsedError;
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/prisma_client.freezed.dart:45683:15: Error: Duplicated parameter name 'id_question_id_participant_id'.
              id_question_id_participant_id});
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/prisma_client.freezed.dart:45680:15: Context: Other parameter named 'id_question_id_participant_id'.
              id_question_id_participant_id,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/prisma_client.freezed.dart:45688:11: Error: 'id_question_id_participant_id' is already declared in this scope.
      get id_question_id_participant_id;
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/prisma_client.freezed.dart:45686:11: Context: Previous declaration of 'id_question_id_participant_id'.
      get id_question_id_participant_id;
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/prisma_client.freezed.dart:45707:13: Error: Duplicated parameter name 'id_question_id_participant_id'.
    Object? id_question_id_participant_id = freezed,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
`

**Comment by medz** [comment]
After my subjective test, #96 belongs to the same bug, you can update to 2.6.1 to see if it has been resolved. If it still exists, you can reopen this issue.
